finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls'))
]

finalproject/student/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("list_results", views.list_results, name="list_results"),
    path("list_booked", views.list_booked, name="list_booked"),
    path("rental/<int:property_id>", views.rental, name="rental"),
    path("profile", views.profile, name="profile"),
    path("create", views.create, name="create"),
    path("register", views.register, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("accept", views.accept, name="accept"),
    path("decline", views.decline, name="decline"),
    path("profile_edit", views.profile_edit, name="profile_edit")
]

finalproject/student/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    pass


def __str__(self):
    return self.username


class Property(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(
        max_length=100, blank=False, null=False, default='')
    description = models.CharField(max_length=200, blank=False)
    price = models.IntegerField(blank=False)
    CITY_CHOICES = [
        ('BERKELEY', 'Berkeley'),
        ('CONCORD', 'Concord'),
        ('FREMONT', 'Fremont'),
        ('HAYWARD', 'Hayward'),
        ('MV', 'Mountain View'),
        ('OAKLAND', 'Oakland'),
        ('PALO ALTO', 'Palo Alto'),
        ('RICHMOND', 'Richmond'),
        ('SC', 'Santa Clara'),
        ('SJ', 'San Jose'),
        ('SF', 'San Francisco'),
        ('SM', 'San Mateo'),
        ('SR', 'San Rafael'),
        ('SR', 'Santa Rosa'),
        ('SV', 'Sunnyvale'),
        ('VALLEJO', 'Vallejo'),
    ]
    city = models.CharField(max_length=50, choices=CITY_CHOICES, blank=False)
    address = models.CharField(max_length=100, blank=False)
    PLACE_CHOICES = [
        ("SR", "Shared room"),
        ("PR", "Private room"),
        ("EP", "Entire place")
    ]
    place = models.CharField(max_length=10, choices=PLACE_CHOICES, blank=False)
    image1 = models.TextField(blank=False)
    image2 = models.TextField(blank=False)
    image3 = models.TextField(blank=False)
    image4 = models.TextField(blank=False)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Amenities(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    wifi = models.BooleanField(default=False)
    kitchen = models.BooleanField(default=False)
    washer = models.BooleanField(default=False)
    bike = models.BooleanField(default=False)
    parking = models.BooleanField(default=False)
    cctv = models.BooleanField(default=False)
    gate = models.BooleanField(default=False)
    wifi_bill = models.IntegerField(default=False)
    water_bill = models.IntegerField(default=False)
    electricity_bill = models.IntegerField(default=False)
    gas_bill = models.IntegerField(default=False)
    heating_bill = models.IntegerField(default=False)

    def __str__(self):
        return self.property.title


class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, default="Pending")
    phone = models.CharField(max_length=20, blank=False)
    message = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return self.user.username

finalproject/student/views.py
from django.contrib.auth.decorators import login_required
from django.db.utils import Error
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.db import IntegrityError
from .models import *
import json


def index(request):
    cities = []
    for property in Property.objects.filter(available=True):
        if property.get_city_display() in cities:
            continue
        else:
            cities.append(property.get_city_display())
    return render(request, 'student/index.html', {
        'cities': cities
    })


def list_results(request):
    city = request.GET.get('city_search')
    if city:
        properties = []
        for property in Property.objects.filter(available=True):
            if property.get_city_display() == city:
                properties.append(property)
        message = f"{city} Rentals"
    else:
        properties = Property.objects.filter(available=True)
        message = "All Bay Area Rentals"
    amenities = Amenities.objects.all()
    return render(request, 'student/results.html', {
        'properties': properties,
        'amenities': amenities,
        'message': message
    })


def list_booked(request):
    properties = Property.objects.filter(available=False)
    amenities = Amenities.objects.all()
    message = "Booked Properties"
    return render(request, 'student/results.html', {
        'properties': properties,
        'amenities': amenities,
        'message': message
    })


@login_required
def rental(request, property_id):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            property = Property.objects.get(id=property_id)
            phone = request.POST['phonenumber']
            message = request.POST['message']
            if len(Booking.objects.filter(property=property, user=user)) == 0:
                new_enquiry = Booking(
                    user=user, property=property, phone=phone, message=message)
                new_enquiry.save()
            else:
                Error("You have already made an enquiry for this property")
            amenities = Amenities.objects.get(property=property)
            booking = Booking.objects.filter(property=property, user=user)
            return HttpResponseRedirect(reverse("rental", args=(property.id,)))
        else:
            property = Property.objects.get(id=property_id)
            amenities = Amenities.objects.get(property=property)
            booking = Booking.objects.filter(property=property, user=user)
            return render(request, 'student/rental.html', {
                'property': property,
                'user': user,
                'amenities': amenities,
                'booking': booking
            })
    else:
        return HttpResponseRedirect(reverse("login_view"))


@login_required
def profile(request):
    user = request.user
    if user.is_authenticated:
        properties = Property.objects.filter(user=user)
        enquiries = Booking.objects.filter(user=user)
        amenities = Amenities.objects.all
        bookers = Booking.objects.filter(property__in=properties)
        return render(request, 'student/profile.html', {
            'user': user,
            'properties': properties,
            'enquiries': enquiries,
            'amenities': amenities,
            'bookers': bookers
        })
    else:
        HttpResponseRedirect(reverse("login_view"))


@login_required
def create(request):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            # Create new property
            title = request.POST['title']
            description = request.POST['description']
            price = request.POST['price']
            city = request.POST['city_category']
            address = request.POST['form-address']
            place = request.POST['place_category']
            image1 = request.POST['image1']
            image2 = request.POST['image2']
            image3 = request.POST['image3']
            image4 = request.POST['image4']
            new_property = Property(user=user, title=title, description=description, price=price, city=city,
                                    address=address, place=place, image1=image1, image2=image2, image3=image3, image4=image4)
            new_property.save()
            wifi = request.POST.get('wifi', False)
            kitchen = request.POST.get('kitchen', False)
            washer = request.POST.get('washer', False)
            bike = request.POST.get('bike', False)
            parking = request.POST.get('parking', False)
            cctv = request.POST.get('cctv', False)
            gate = request.POST.get('gate', False)
            wifi_bill = request.POST.get('wifi-bill', False)
            water = request.POST.get('water', False)
            electricity = request.POST.get('electricity', False)
            gas = request.POST.get('gas', False)
            heating = request.POST.get('heating', False)
            amenities = Amenities(property=new_property, wifi=wifi == 'wifi', kitchen=kitchen == 'kitchen', washer=washer == 'washer', bike=bike == 'bike', parking=parking == 'parking', cctv=cctv == 'cctv',
                                  gate=gate == 'gate', wifi_bill=wifi_bill == 'wifi-bill', water_bill=water == 'water', electricity_bill=electricity == 'electricity', gas_bill=gas == 'gas', heating_bill=heating == 'heating')
            amenities.save()
            return render(request, 'student/create.html', {
                'message': 'Property created!'
            })
        else:
            city_category = Property.CITY_CHOICES
            place_category = Property.PLACE_CHOICES
            return render(request, 'student/create.html', {
                'city_category': city_category,
                'place_category': place_category
            })
    else:
        return HttpResponseRedirect(reverse("login_view"))


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "student/login.html", {
                "message": "Invalid email and/or password."
            })
    else:
        return render(request, "student/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "student/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(
                username=username, first_name=firstname, last_name=lastname, email=email, password=password)
            user.save()
        except IntegrityError:
            return render(request, "student/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "student/register.html")


@csrf_exempt
def accept(request):
    data = json.loads(request.body)
    booking_id = data["booking_id"]
    booking = Booking.objects.get(id=booking_id)
    booking.status = "Confirmed"
    booking.save()
    property = Property.objects.get(id=booking.property.id)
    property.available = False
    property.save()
    return HttpResponseRedirect(reverse("profile"))


@csrf_exempt
def decline(request):
    data = json.loads(request.body)
    booking_id = data["booking_id"]
    booking = Booking.objects.get(id=booking_id)
    booking.status = "Declined"
    booking.save()
    return HttpResponseRedirect(reverse("profile"))


@csrf_exempt
def profile_edit(request):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            data = json.loads(request.body)
            action = data["action"]
            if action == "first_name":
                first_name = data["first_name"]
                user.first_name = first_name
                user.save()
            elif action == "last_name":
                last_name = data["last_name"]
                user.last_name = last_name
                user.save()
            elif action == "email":
                email = data["email"]
                user.email = email
                user.save()
            return HttpResponseRedirect(reverse("profile"))
    else:
        return HttpResponseRedirect(reverse("login_view"))

finalproject/student/templates/student/index.html
{% extends "student/layout.html" %} {% block title %} Student Rentals
{%endblock%} {% block body %}
<div class="index-content">
  Find a perfect place for your college experience
</div>

<form class="search" method="GET" action="{% url 'list_results' %}">
  {% csrf_token %}
  <select
    type="search"
    placeholder="Search by city"
    name="city_search"
    required
  >
    <option value="" disabled selected>Search by city</option>
    {% for city in cities %}
    <option value="{{city}}">{{city}}</option>
    {% endfor %}
  </select>
  <button type="submit">Search</button>
</form>
<div class="explore-all">
  <div class="explore-or">OR</div>
  <a class="explore-all-button" href="{% url 'list_results' %}">Explore all</a>
</div>

<footer>
  <div class="small">
    Rent a place for your 2022-2023 college year in San Francisco&Bay Area
  </div>
</footer>
{% endblock %}

finalproject/student/templates/student/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- This sets the width of the page to follow the screen-width of the device and zoom out to fit -->
    <link href="{% static 'student/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'student/responsive.css' %}" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar">
      <a href="{% url 'index' %}" class="navbar-brand"
        ><div class="navbar-brand">Bay Area Student Rentals</div></a
      >
      <ul class="navbar-list">
        <li>
          <a href="{% url 'index' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'list_booked' %}">Booked properties</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'profile' %}">Profile</a>
        </li>
        <li>
          <a href="{% url 'create' %}">Become a host</a>
        </li>
        <li>
          <a href="{% url 'logout' %}">Log out</a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'register' %}">Register</a>
        </li>
        <li>
          <a href="{% url 'login' %}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <main>{% block body %} {% endblock %}</main>
  </body>
</html>

finalproject/student/templates/student/login.html
{% extends "student/layout.html" %} {% block body %}

<div class="results-heading">Login</div>
<hr />
{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'login' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <input
      autofocus
      class="form-control"
      type="text"
      name="username"
      placeholder="Username"
    />
  </div>
  <div class="form-group">
    <input
      class="form-control"
      type="password"
      name="password"
      placeholder="Password"
    />
  </div>
  <button type="submit">Log In</button>
</form>

<div class="underbutton">
  Don't have an account? <a href="{% url 'register' %}">Register here.</a>
</div>

{% endblock %}

finalproject/student/templates/student/profile.html
{% extends "student/layout.html" %} 

{% block title %} Your profile {%endblock%}

{% block body %}
<div class="results-heading">Hello, {{user.first_name}}!</div>
<div class="profile-links">
    <a class="profile-big" id="profile-enquiries">Your inquiries</a>
    <a class="profile-big" id="profile-properties">Your properties</a>
    <a class="profile-big" id="profile-edit">Edit profile</a>
</div>


<div class="profile-links-content" id="enquiries">
    {% if enquiries %}
    {% for enquiry in enquiries %}
    <hr>
    <a href="{% url 'rental' enquiry.property.id %}" class="result">
        <div class="result-image">
            <img src="{{enquiry.property.image1}}" alt="image of the property">
        </div>
        <div class="result-content">
            <div class="small">{{enquiry.property.get_place_display}}</div>
            <div class="big">{{enquiry.property.get_city_display}} • {{enquiry.property.title}}</div>
            <hr class="hr-result">
            <ul class="amenities">
                {% for amenity in amenities %}
                {% if amenity.property == enquiry.property %}
                {% if amenity.wifi == True %}
                <li class="small">Wifi</li>
                {% endif %}
                {% if amenity.washer == True %}
                <li class="small">Washer</li>
                {% endif %}
                {% if amenity.kitchen == True %}
                <li class="small">Kitchen</li>
                {% endif %}
                {% if amenity.bike == True %}
                <li class="small">Bike Storage</li>
                {% endif %}
                {% if amenity.parking == True %}
                <li class="small">Parking</li>
                {% endif %}
                {% endif %}
                {% endfor %}
            </ul>
            <div class="price">
                <span id="price">${{enquiry.property.price}}</span>
                <span>/ month</span>
            </div>
        </div>
    </a>
    <div class="rental-approval" id="{{enquiry.status}}">{{enquiry.status}}</div>
    {% endfor %}
    {% else %}
    <hr>
    <div>You haven't made any inquiries</div>
    {% endif %}
</div>


<div class="profile-links-content" id="properties">
    {% if properties %}
    {% for property in properties %}
    <hr>
    <a href="{% url 'rental' property.id %}" class="result">
        <div class="result-image">
            <img src="{{property.image1}}" alt="image of the property">
        </div>
        <div class="result-content">
            <div class="small">{{property.get_place_display}}</div>
            <div class="big">{{property.get_city_display}} • {{property.title}}</div>
            <hr class="hr-result">
            <ul class="amenities">
                {% for amenity in amenities %}
                {% if amenity.property == property %}
                {% if amenity.wifi == True %}
                <li class="small">Wifi</li>
                {% endif %}
                {% if amenity.washer == True %}
                <li class="small">Washer</li>
                {% endif %}
                {% if amenity.kitchen == True %}
                <li class="small">Kitchen</li>
                {% endif %}
                {% if amenity.bike == True %}
                <li class="small">Bike Storage</li>
                {% endif %}
                {% if amenity.parking == True %}
                <li class="small">Parking</li>
                {% endif %}
                {% endif %}
                {% endfor %}
            </ul>
            <div class="price">
                <span id="price">${{property.price}}</span>
                <span>/ month</span>
            </div>
        </div>
    </a>
    {% for booker in bookers %}
    {% if booker.property == property %}
    <div class="bookers">
        <div class="booker-info">
            <div class="small">{{booker.user.first_name}} {{booker.user.last_name}}</div>
            <div class="small">{{booker.user.email}} • {{booker.phone}}</div>
            <div>{{booker.message}}</div>
        </div>
        <div class="booker-button">
            {% if booker.status == 'Pending' %}
            <button id="Confirmed" data-id="{{booker.id}}" class="Confirmed-{{booker.id}}">Accept</button>
            <button id="Declined" data-id="{{booker.id}}" class="Declined-{{booker.id}}">Decline</button>
            <button id="button-finished" data-id="{{booker.id}}" class="Finished-{{booker.id}}"></button>
            {% else %}
            <button id="{{booker.status}}" class="button-finished">{{booker.status}}</button>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
    {% endfor %}
    {% else %}
    <hr>
    <div>You don't have any properties</div>
    {% endif %}
</div>


<div class="edit-content" id="edit">
    <hr>
    <div class="form-group">
        <label for="username">Username</label>
        <div class="input-group">
            <input type="text" name="username" id="username" value="{{user.username}}" disabled>
        </div>
    </div>

    <form class="profile-change" >
        {% csrf_token %}
        <div class="form-group">
            <label for="first_name">First name</label>
            <div class="input-group">
                <input type="text" name="first_name" id="first_name" value="{{user.first_name}}">
                <input type="submit" class="change-button" value="Save" id="first-change"></input>
                <span class="success-edit" id="success-first">First name changed successfully!</span>
            </div>
            
        </div>
    </form>
    
    <form class="profile-change" >
        {% csrf_token %}
        <div class="form-group">
            <label for="last_name">Last name</label>
            <div class="input-group">
                <input type="text" name="last_name" id="last_name" value="{{user.last_name}}" >
                <input type="submit" class="change-button" value="Save" id="last-change"></input>
                <span class="success-edit" id="success-last">Last name changed successfully!</span>
            </div>
        </div>
    </form>

    <form class="profile-change" >
        {% csrf_token %}
        <div class="form-group">
            <label for="email">Email</label>
            <div class="input-group">
                <input type="text" name="email" id="email" value="{{user.email}}" >
                <input type="submit" class="change-button" value="Save" id="email-change"></input>
                <span class="success-edit" id="success-email">Email changed successfully!</span>
            </div>
        </div>
    </form>
</div>

<script src="/static/student/profile.js"></script>
{% endblock %}

finalproject/student/templates/student/rental.html
{% extends "student/layout.html" %} {% block title %} Queen room with shared
bathroom {%endblock%} {% block body %}
<div class="results-heading">{{property.title}}</div>
<div class="small">
  {{property.get_place_display}} • {{property.get_city_display}}
</div>
<div class="image-gallery">
  <div class="image-container">
    <img
      src="{{property.image1}}"
      alt="Queen room with shared bathroom"
      id="expandedImage"
    />
  </div>
  <div class="images-column">
    <div class="image-single">
      <img src="{{property.image1}}" alt="{{property.title}}" id="smallImage" />
    </div>
    <div class="image-single">
      <img src="{{property.image2}}" alt="{{property.title}}" id="smallImage" />
    </div>
    <div class="image-single">
      <img src="{{property.image3}}" alt="{{property.title}}" id="smallImage" />
    </div>
    <div class="image-single">
      <img src="{{property.image4}}" alt="{{property.title}}" id="smallImage" />
    </div>
  </div>
</div>
<div class="rental-content">
  <div class="rental-content-info">
    <div class="big" id="rental-big">Property details</div>
    <div class="info">{{property.description}}</div>
    <div class="big" id="rental-big">Address</div>
    <span class="small">{{property.address}}</span>
    <hr />
    <div class="big" id="rental-big">Amenities</div>
    <ul class="amenities">
      {% if amenities.wifi == True %}
      <li class="small">Wifi</li>
      {% endif %} {% if amenities.kitchen == True %}
      <li class="small">Kitchen</li>
      {% endif %} {% if amenities.washer == True %}
      <li class="small">Washer</li>
      {% endif %} {% if amenities.bike == True %}
      <li class="small">Bike storage</li>
      {% endif %} {% if amenities.parking == True %}
      <li class="small">Parking</li>
      {% endif %}
    </ul>
    <div class="big" id="rental-big">Security & Safety</div>
    {% if amenities.cctv == True %}
    <div id="included">
      <ul class="amenities">
        <li class="small">CCTV / Surveillance Cameras</li>
      </ul>
    </div>
    {% else %}
    <div id="notIncluded">
      <ul class="amenities">
        <li class="small">CCTV / Surveillance Cameras</li>
      </ul>
    </div>
    {% endif %} {% if amenities.gate == True %}
    <div id="included">
      <ul class="amenities">
        <li class="small">Controlled Access Gate</li>
      </ul>
    </div>
    {% else %}
    <div id="notIncluded">
      <ul class="amenities">
        <li class="small">Controlled Access Gate</li>
      </ul>
    </div>
    {% endif %}
    <div class="big" id="rental-big">Bills included</div>
    {% if amenities.wifi_bill == True %}
    <div id="included">
      <ul class="amenities">
        <li class="small">Wifi</li>
      </ul>
    </div>
    {% else %}
    <div id="notIncluded">
      <ul class="amenities">
        <li class="small">Wifi</li>
      </ul>
    </div>
    {% endif %} {% if amenities.water_bill == True %}
    <div id="included">
      <ul class="amenities">
        <li class="small">Water</li>
      </ul>
    </div>
    {% else %}
    <div id="notIncluded">
      <ul class="amenities">
        <li class="small">Water</li>
      </ul>
    </div>
    {% endif %} {% if amenities.electricity_bill == True %}
    <div id="included">
      <ul class="amenities">
        <li class="small">Electricity</li>
      </ul>
    </div>
    {% else %}
    <div id="notIncluded">
      <ul class="amenities">
        <li class="small">Electricity</li>
      </ul>
    </div>
    {% endif %} {% if amenities.gas_bill == True %}
    <div id="included">
      <ul class="amenities">
        <li class="small">Gas</li>
      </ul>
    </div>
    {% else %}
    <div id="notIncluded">
      <ul class="amenities">
        <li class="small">Gas</li>
      </ul>
    </div>
    {% endif %} {% if amenities.heating_bill == True %}
    <div id="included">
      <ul class="amenities">
        <li class="small">Heating</li>
      </ul>
    </div>
    {% else %}
    <div id="notIncluded">
      <ul class="amenities">
        <li class="small">Heating</li>
      </ul>
    </div>
    {% endif %}
  </div>
  {% if property.user != user %} {% if property.available == True %}
  <div class="rental-book">
    <div class="price">
      <span id="price">${{property.price}}</span>
      <span>/ month</span>
    </div>
    <div class="book-form">
      <form action="{% url 'rental' property.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="name">First name</label>
          <input
            type="text"
            class="form-control"
            id="firstname"
            name="firstname"
            placeholder="Enter first name"
            value="{{user.first_name}}"
            disabled
          />
        </div>
        <div class="form-group">
          <label for="name">Last name</label>
          <input
            type="text"
            class="form-control"
            id="lastname"
            name="lastname"
            placeholder="Enter last name"
            value="{{user.last_name}}"
            disabled
          />
        </div>
        <div class="form-group">
          <label for="email">Email address</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
            value="{{user.email}}"
            disabled
          />
        </div>
        {% if booking %}
        <div class="form-group">
          <label for="phone">Phone number</label>
          <input
            type="text"
            class="form-control"
            id="phone"
            name="phonenumber"
            placeholder="Enter phone number"
            value="{{booking.0.phone}}"
            disabled
          />
        </div>
        <div class="form-group">
          <label for="message">Message</label>
          <textarea
            class="form-control"
            id="message"
            name="message"
            rows="3"
            placeholder="Enter message"
            disabled
          >
{{booking.0.message}}</textarea
          >
        </div>
        <button
          type="submit"
          class="button-rental"
          id="{{booking.0.status}}"
          disabled
        >
          Inquiry status: {{booking.0.status}}
        </button>
        {% else %}
        <div class="form-group">
          <label for="phone">Phone number</label>
          <input
            type="text"
            class="form-control"
            id="phone"
            name="phonenumber"
            placeholder="Enter phone number"
            autofill="off"
          />
        </div>
        <div class="form-group">
          <label for="message">Message</label>
          <textarea
            class="form-control"
            id="message"
            name="message"
            rows="3"
            placeholder="Enter message"
          ></textarea>
        </div>
        <button type="submit" class="button-rental">Make inquiry</button>
        {% endif %}
      </form>
    </div>
  </div>
  {% endif %} {% endif %}
</div>

<script src="/static/student/image.js"></script>
{% endblock %}

finalproject/student/templates/student/results.html
{% extends "student/layout.html" %} {% block title %} Rentals San Francisco
{%endblock%} {% block body %}
<div class="results-heading">{{message}}</div>
<div class="results-list">
  {% for property in properties %}
  <hr />
  <a href="{% url 'rental' property.id %}" class="result">
    <div class="result-image">
      <img src="{{property.image1}}" alt="image of the property" />
    </div>
    <div class="result-content">
      <div class="small">{{property.get_place_display}}</div>
      <div class="big">{{property.get_city_display}} • {{property.title}}</div>
      <hr class="hr-result" />
      <ul class="amenities">
        {% for amenity in amenities %}
        {% if amenity.property == property %}
        {%if amenity.wifi == True %}
        <li class="small">Wifi</li>
        {% endif %}
        {% if amenity.washer == True %}
        <li class="small">Washer</li>
        {% endif %}
        {% if amenity.kitchen == True %}
        <li class="small">Kitchen</li>
        {% endif %}
        {% if amenity.bike == True %}
        <li class="small">Bike Storage</li>
        {% endif %}
        {% if amenity.parking == True %}
        <li class="small">Parking</li>
        {% endif %}
        {% endif %}
        {% endfor %}
      </ul>
      <div class="price">
        <span id="price">${{property.price}}</span>
        <span>/ month</span>
      </div>
    </div>
  </a>
  {% endfor %}
</div>

{% endblock %}